config/routes.rb
Rails.application.routes.draw do
  
  get 'project_documents/predesign'

  get 'project_documents/design'

  get 'project_documents/tendering'

  get 'project_documents/construction'

  get "predesign" => "project_documents#predesign"

  resources :announcements

  resources :exterior_reports
  resources :messages
  resources :interior_circulars
  resources :circulars
  resources :reports
  resources :interior_reports
  resources :admin_circulars
  resources :admin_reports
  resources :ministry_reports

  resources :projects do
    resources :pictures
    resources :teams
    resources :months
    resources :statuses
  end
  
  

  resources :vacations

  resources :experiences

  resources :profiles

  devise_for :users

  devise_scope :user do
   root :to => 'devise/sessions#new'
end

  get "main" => "pages#main"
  get "projects" => "pages#projects"
  get "project_docs" => "pages#project_docs"
  get "search" => "pages#search"
  get "reports" => "pages#reports"
  get "feedback" => "pages#feedback"
  get "project_documents" => "pages#project_documents"

 

  get "tasks" => "subpages#tasks"
  get "vacations" => "subpages#vacations"
  get "active" => "subpages#active"
  get "presignature" => "subpages#presignature"
  get "develop" => "subpages#develop" 
  get "proposed" => "subpages#proposed" 
  get "archive" => "subpages#archive" 
  get "monthly_template" => "subpages#monthly_template" 
  get "development2" => "subpages#development2" 
  get "phase1" => "subpages#phase1" 
  get "phase2" => "subpages#phase2"  
  get "phase3" => "subpages#phase3" 
  get "phase4" => "subpages#phase4" 
  get "proposed2" => "subpages#proposed2" 

get '/tasks', :to => redirect('/tasks.html')

end

app/models/admin_circular.rb
class AdminCircular < ActiveRecord::Base

	belongs_to :user
	has_attached_file :report,
	path: ":rails_root/public/system/:attachment/:id/:style/:filename",
 	url: "/system/:attachment/:id/:style/:filename"
	validates_attachment_content_type :report, :content_type => ['application/pdf']
	
end

app/models/admin_report.rb
class AdminReport < ActiveRecord::Base

	belongs_to :user
	has_attached_file :report,
	path: ":rails_root/public/system/:attachment/:id/:style/:filename",
 	url: "/system/:attachment/:id/:style/:filename"
	validates_attachment_content_type :report, :content_type => ['application/pdf']
	
end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
	belongs_to :user
end

app/models/circular.rb
class Circular < ActiveRecord::Base

	belongs_to :user
	has_attached_file :report,
	path: ":rails_root/public/system/:attachment/:id/:style/:filename",
 	url: "/system/:attachment/:id/:style/:filename"
	validates_attachment_content_type :report, :content_type => ['application/pdf']
	
end

app/models/experience.rb
class Experience < ActiveRecord::Base

	belongs_to :profile 

end

app/models/exterior_report.rb
class ExteriorReport < ActiveRecord::Base

	belongs_to :user
	has_attached_file :report,
	path: ":rails_root/public/system/:attachment/:id/:style/:filename",
 	url: "/system/:attachment/:id/:style/:filename"
	validates_attachment_content_type :report, :content_type => ['application/pdf']
	
end

app/models/message.rb
class Message < ActiveRecord::Base

	belongs_to :user
	has_attached_file :report,
	path: ":rails_root/public/system/:attachment/:id/:style/:filename",
 	url: "/system/:attachment/:id/:style/:filename"
	validates_attachment_content_type :report, :content_type => ['application/pdf']
	
end

app/models/ministry_report.rb
class MinistryReport < ActiveRecord::Base

	belongs_to :user
	has_attached_file :report,
	path: ":rails_root/public/system/:attachment/:id/:style/:filename",
 	url: "/system/:attachment/:id/:style/:filename"
	validates_attachment_content_type :report, :content_type => ['application/pdf']
	
end

app/models/month.rb
class Month < ActiveRecord::Base

	belongs_to :user
	belongs_to :project
	has_attached_file :report,
	path: ":rails_root/public/system/:attachment/:id/:style/:filename",
 	url: "/system/:attachment/:id/:style/:filename"
	validates_attachment_content_type :report, :content_type => ['application/pdf']


end

app/models/picture.rb
class Picture < ActiveRecord::Base
	
 belongs_to :project

 has_attached_file :image,
 path: ":rails_root/public/system/:attachment/:id/:style/:filename",
 url: "/system/:attachment/:id/:style/:filename",
:styles => { :medium => "900x900>", :thumb => "300x300>" }

 validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", 'application/pdf']

end

app/models/profile.rb
class Profile < ActiveRecord::Base

	belongs_to :users
	has_many :experiences, :dependent => :destroy

	accepts_nested_attributes_for :experiences, :reject_if => lambda { |a| a[:title].blank? }, allow_destroy: true

	validates_associated :experiences

	validates :name, :civil, :date_of_employment, :mobile, :work_email, :personal_email, :internal_no, :academic_degree, :major, presence: true
	validates :civil, length: { is: 12 }
	validates :mobile, length: { is: 8 }
	validates :folder, length: { is: 5 }


end

app/models/project.rb
class Project < ActiveRecord::Base

  has_many :pictures,  :dependent => :destroy
  has_many :teams, :dependent => :destroy
  has_many :months, :dependent => :destroy
  has_many :statuses, :dependent => :destroy


	accepts_nested_attributes_for :pictures, :reject_if => lambda { |a| a[:image].blank? }, allow_destroy: true
	accepts_nested_attributes_for :teams, :reject_if => lambda { |a| a[:member].blank? }, allow_destroy: true
	accepts_nested_attributes_for :months, :reject_if => lambda { |a| a[:month_range].blank? }, allow_destroy: true
	accepts_nested_attributes_for :statuses, :reject_if => lambda { |a| a[:title].blank? }, allow_destroy: true

end

app/models/report.rb
class Report < ActiveRecord::Base

	belongs_to :user
	has_attached_file :file,
	path: ":rails_root/public/system/:attachment/:id/:style/:filename",
 	url: "/system/:attachment/:id/:style/:filename"
	validates_attachment_content_type :file, :content_type => ['application/pdf']

end

app/models/status.rb
class Status < ActiveRecord::Base

	belongs_to :project
	belongs_to :user
end

app/models/team.rb
class Team < ActiveRecord::Base

	belongs_to :project
	belongs_to :user
	validates :member, uniqueness: { scope: :project_id }

end

  
    

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile, :dependent => :destroy
  has_and_belongs_to_many :teams, :dependent => :destroy
  has_many :statuses, :dependent => :destroy
  has_many :exterior_reports
  has_many :admin_circulars
  has_many :admin_reports
  has_many :circulars
  has_many :interior_circulars
  has_many :interior_reports
  has_many :messages
  has_many :ministry_reports
  has_many :months
  has_many :reports
  has_many :announcements

end

app/models/vacation.rb
class Vacation < ActiveRecord::Base

	def days_spread
	  (end_date.to_date - start_date.to_date).to_i
	end

end

app/controllers/Circulars and Reports/ministry_reports_controller.rb
class MinistryReportsController < ApplicationController
  before_action :set_ministry_report, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]

  respond_to :html

  def index
    @ministry_reports = MinistryReport.all
    respond_with(@ministry_reports)
  end

  def show
    respond_with(@ministry_report)
  end

  def new
    @ministry_report = MinistryReport.new
    respond_with(@ministry_report)
  end

  def edit
  end

  def create
    @ministry_report = MinistryReport.new(ministry_report_params)
    @ministry_report.user = current_user
    if @ministry_report.save
      redirect_to project_docs_path, notice: 'Successfully Added Report'
    else
      render action: 'new'
    end
  end

  def update
    @ministry_report.update(ministry_report_params)
    redirect_to project_docs_path, :notice => "Report Updated"
  end

  def destroy
    @ministry_report.destroy
    redirect_to project_docs_path, :notice => "Report Deleted"
  end

  private
    def set_ministry_report
      @ministry_report = MinistryReport.find(params[:id])
    end

    def ministry_report_params
      params.require(:ministry_report).permit(:number, :subject, :date_issued, :report)
    end
end

app/helpers/ministry_reports_helper.rb
module MinistryReportsHelper
end

app/helpers/months_helper.rb
module MonthsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/ministry_reports/_form.html.erb
<%= bootstrap_form_for(@ministry_report, :html => { :multipart => true }, layout: :horizontal) do |f| %>
  <% if @ministry_report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ministry_report.errors.count, "error") %> prohibited this ministry_report from being saved:</h2>

      <ul>
      <% @ministry_report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">

    <%= f.text_field :number %>
  </div>
  <div class="field">

    <%= f.text_area :subject %>
  </div>
  <div class="field">

    <%= f.date_select :date_issued %>
  </div>
  <div class="actions">
    <%= f.file_field(:report) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ministry_reports/edit.html.erb
<div class="row">
	<div class="col-md-offset-2 col-md-8">

		<h3>#تعديل قرار وزاري رقم <%= @ministry_report.number %></h3>

		<%= render 'form' %>

		<%= link_to 'Back', project_docs_path %>

	</div>
</div>

app/views/ministry_reports/index.html.erb
<h1>Listing ministry_reports</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Subject</th>
      <th>Date issued</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ministry_reports.each do |ministry_report| %>
      <tr>
        <td><%= ministry_report.number %></td>
        <td><%= ministry_report.subject %></td>
        <td><%= ministry_report.date_issued %></td>
        <td><%= link_to 'Show', ministry_report %></td>
        <td><%= link_to 'Edit', edit_ministry_report_path(ministry_report) %></td>
        <td><%= link_to 'Destroy', ministry_report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ministry report', new_ministry_report_path %>

app/views/ministry_reports/new.html.erb
<div class="row">
	<div class="col-md-offset-2 col-md-8">

		<h3>قرار وزاري جديد</h3>

		<%= render 'form' %>

		<%= link_to 'Back', project_docs_path %>

	</div>
</div>

app/views/ministry_reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @ministry_report.number %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @ministry_report.subject %>
</p>

<p>
  <strong>Date issued:</strong>
  <%= @ministry_report.date_issued %>
</p>

<%= link_to 'Edit', edit_ministry_report_path(@ministry_report) %> |
<%= link_to 'Back', ministry_reports_path %>