config/routes.rb
Rails.application.routes.draw do
  
  get 'project_documents/predesign'

  get 'project_documents/design'

  get 'project_documents/tendering'

  get 'project_documents/construction'

  get "predesign" => "project_documents#predesign"

  resources :announcements

  resources :exterior_reports
  resources :messages
  resources :interior_circulars
  resources :circulars
  resources :reports
  resources :interior_reports
  resources :admin_circulars
  resources :admin_reports
  resources :ministry_reports

  resources :projects do
    resources :pictures
    resources :teams
    resources :months
    resources :statuses
  end
  
  

  resources :vacations

  resources :experiences

  resources :profiles

  devise_for :users

  devise_scope :user do
   root :to => 'devise/sessions#new'
end

  get "main" => "pages#main"
  get "projects" => "pages#projects"
  get "project_docs" => "pages#project_docs"
  get "search" => "pages#search"
  get "reports" => "pages#reports"
  get "feedback" => "pages#feedback"
  get "project_documents" => "pages#project_documents"

 

  get "tasks" => "subpages#tasks"
  get "vacations" => "subpages#vacations"
  get "active" => "subpages#active"
  get "presignature" => "subpages#presignature"
  get "develop" => "subpages#develop" 
  get "proposed" => "subpages#proposed" 
  get "archive" => "subpages#archive" 
  get "monthly_template" => "subpages#monthly_template" 
  get "development2" => "subpages#development2" 
  get "phase1" => "subpages#phase1" 
  get "phase2" => "subpages#phase2"  
  get "phase3" => "subpages#phase3" 
  get "phase4" => "subpages#phase4" 
  get "proposed2" => "subpages#proposed2" 

get '/tasks', :to => redirect('/tasks.html')

end

app/models/project.rb
class Project < ActiveRecord::Base

  has_many :pictures,  :dependent => :destroy
  has_many :teams, :dependent => :destroy
  has_many :months, :dependent => :destroy
  has_many :statuses, :dependent => :destroy


	accepts_nested_attributes_for :pictures, :reject_if => lambda { |a| a[:image].blank? }, allow_destroy: true
	accepts_nested_attributes_for :teams, :reject_if => lambda { |a| a[:member].blank? }, allow_destroy: true
	accepts_nested_attributes_for :months, :reject_if => lambda { |a| a[:month_range].blank? }, allow_destroy: true
	accepts_nested_attributes_for :statuses, :reject_if => lambda { |a| a[:title].blank? }, allow_destroy: true

end

app/controllers/Projects/months_controller.rb
class MonthsController < ApplicationController
  before_action :set_month, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]
  before_action :set_project
  respond_to :html

  def index
    @months = Month.all
    respond_with(@month)
  end

  def show
    respond_with(@month)
  end

  def new
    @month = Month.new
    respond_with(@month)
  end

  def edit
  end

  def create
    @project = Project.find(params[:project_id])
    @month = @project.months.build(month_params)
    @month.user = current_user
    if @month.save
      redirect_to @project, notice: 'Successfully Added Monthly Report'
    else
      render action: 'new'
    end
  end

  def update
    @month.update(month_params)
    redirect_to @project, :notice => "Report Updated"
  end

  def destroy
    @month.destroy
    redirect_to @project, :notice => "Report Deleted"
  end

  private
    def set_month
      @month = Month.find(params[:id])
    end

    def set_project 
      @project = Project.find(params[:project_id])
    end 

    def month_params
      params.require(:month).permit(:month_time, :phase, :project_id, :report)
    end
end

app/controllers/Projects/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @pictures = Picture.all
    respond_with(@pictures)
  end

  def show
    respond_with(@picture)
  end

  def new
    @picture = Picture.new
    respond_with(@picture)
  end

  def edit
  end

  def create
    @picture = Picture.new(picture_params)
    @picture.save
    respond_with(@picture)
  end

  def update
    @picture.update(picture_params)
    respond_with(@picture)
  end

  def destroy
    @picture.destroy
    respond_with(@picture)
  end

  private
    def set_picture
      @picture = Picture.find(params[:id])
    end

    def picture_params
      params.require(:picture).permit(:image, :id, :project_id)
    end
end

app/controllers/Projects/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @projects = Project.all.order("created_at ASC")
    respond_with(@projects)
  end

  def show
    @project = Project.find(params[:id])
    @months = @project.months.all.paginate(:page => params[:page], :per_page => 3)

  end

  def new
    @project = Project.new
    @project.pictures.build
    @project.teams.build
  end



  def edit
  end

  def create
    @project = Project.new(project_params)
    if @project.save
    flash[:notice] = "Successfully created project."
    redirect_to @project
    else
    render :action => 'new'
    end

  end

  def update
    @project.update(project_params)
    respond_with(@project)
  end

  def destroy
    @project.destroy
    respond_with(@project)
  end

  private
    def set_project
      @project = Project.find(params[:id])
    end


    def project_params
      params.require(:project).permit(:id, :title, :description, :phase, :location, :contractor, :designer, :client, :area, :budget, :project_start, :construction_period, :expected_date, :picture_id, :status_id, pictures_attributes: [:id, :image, :_destroy], teams_attributes: [:project_id, :user_id, :id, :member, :role, :_destroy], months_attributes: [:month_time, :phase, :id, :_destroy], statuses_attributes: [:id, :status_update, :status_title, :user_id, :_destroy] )
    end
end

app/controllers/Projects/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]
  before_action :set_project
  respond_to :html

  def index
    @statuses = Status.all
    respond_with(@statuses)
  end

  def show
    respond_with(@status)
  end

  def new
    @status = Status.new
    respond_with(@status)
  end

  def edit
  end

  def create
    @project = Project.find(params[:project_id])
    @status = @project.statuses.new(status_params)
    @status.user = current_user
    if @status.save
      redirect_to @project, notice: 'Successfully Added Status Update'
    else
      render action: 'new'
    end

  end

  def update
    @status.update(status_params)
    respond_with(@status)
  end

  def destroy
    @status.destroy
    redirect_to @project, :notice => "Status Deleted"
  end

  private
    def set_status
      @status = Status.find(params[:id])
    end

    def set_project 
      @project = Project.find(params[:project_id])
    end 

    def status_params
      params.require(:status).permit(:status_update, :status_title, :user_id)
    end
end

app/controllers/Projects/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]
  before_action :set_project
  respond_to :html

  def index
    @teams = Team.all
    respond_with(@teams)
  end

  def show
    respond_with(@team)
  end

  def new
    @project = Project.find(params[:project_id])
    @team = @project.teams.new

  end

  def edit
    
  end

  def create
    @project = Project.find(params[:project_id])
    @team = @project.teams.new(team_params)
   if @team.save
      redirect_to @project, notice: 'Successfully Joined Project'
    else
      render action: 'new'
    end
  end


  def update
    @team.update(team_params)
    if @team.save
      redirect_to @project, :notice => "Team Updated"
    end
  end

  def destroy
    @team.destroy
    redirect_to @project, :notice => "Removed from Project"
  end

  private
    def set_team
      @team = Team.find(params[:id])
    end

    def set_project 
      @project = Project.find(params[:project_id])
    end 

    def team_params
      params.require(:team).permit(:id, :user_id, :member, :role, :project_id )
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper


end

app/views/projects/_form.html.erb
<%= bootstrap_nested_form_for(@project, :html => {:multipart => true}, layout: :horizontal)   do |f| %>



  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-inputs">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">General Info</h4>
      </div>
    <div class="panel-body">
      <%= f.text_field :title %>
      <%= f.select :phase, [["Phase 1"], ["Phase 2"], ["Phase 3"]],  { label: "Phase"}, { class: "selectpicker" } %>
      <%= f.text_field :location %>
      <%= f.number_field :area, label: "Area (m2)" %>
      <%= f.text_field :client %>
      <%= f.text_field :designer %>
      <%= f.text_field :contractor %>
      <%= f.text_area :description, {size: "20x10"} %>
    </div>
  </div>
      
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">Schedule Info</h4>
    </div>
  <div class="panel-body">
      <%= f.date_field :project_start, label: "Project Start Date" %>
      <%= f.date_field :expected_date, label: "Expected Completion Date" %>
      <%= f.date_field :signature_date, label: "Date of Contract Signature" %>
      <%= f.number_field :construction_period, label: "Construction Period (Months)" %>
   </div>
  </div>


<div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">Budget Info</h4>
    </div>
  <div class="panel-body">
      <%= f.number_field :budget, label: "Designated Budget" %>
      <%= f.number_field :design_cost, label: "Design Cost" %>
      <%= f.number_field :execution_cost, label: "Execution Cost" %>

     </div>
  </div>


<div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">Team Information</h4>
    </div>
  <div class="panel-body">
      <%= f.fields_for :teams do |builder| %>

     
      <%= builder.collection_select :member, User.all, :employee_name, :employee_name, { prompt: "Please select", :selected => params[:user], label: "Employee" } %> 
      <%= builder.select :role, [["Project Manager"], ["Assistant"], ["Other"]],  { label: "Role"}, { class: "selectpicker" } %>

      <p>
        <%= builder.link_to_remove "Remove" %>
      </p>
      <% end %>
      <%= f.link_to_add "Add Team Member", :teams %>
 </div>
  </div>

    


<div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">Images</h4>
    </div>
  <div class="panel-body">
  <%= f.fields_for :pictures do |builder| %>

     
      <p>
        <%= builder.file_field(:image) %>
      </p>

      <p>
      <%= builder.link_to_remove "Remove" %>
      </p>

  <% end %>

  <p>
   <%= f.link_to_add "Add Images", :pictures %>
 </p>
 </div>
  </div>

 <div class="form-actions">
      <%= f.button :submit %>
    </div>
  </div>
<% end %>


 

app/views/projects/edit.html.erb
<div class="row">
	<div class="col-md-offset-1 col-md-10">


		<h3>Editing project</h3>

		<%= render 'form' %>

		<%= link_to 'Show', @project %> |
		<%= link_to 'Back', projects_path %>

	</div>
</div>

app/views/projects/index.html.erb
<div class="new-project">
  <p>
   <%= link_to 'New Project', new_project_path, class: "btn btn-primary btn-sm" %>
  </p>
</div>


<div id="pictures">
  <% @projects.each do |project| %>

  <div class="col-md-4">

    <div class="box panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= project.title %></h3>
      </div>
      <div class="image">
        <% if !project.pictures.empty? %>
         <%= link_to image_tag(project.pictures.first.image.url(:thumb)), project %>
        <% end %>
      </div>
      <div class="panel-body">

        <p>
          <strong>Progress:</strong>
          <%= progress_bar 0.6, label: true, alternative: 'info', striped: true %>
        </p>


        <p>
          <strong>Phase:</strong>
          <%= project.phase %>
        </p>


        <%= link_to 'Show', project %> |
        <%= link_to 'Edit', edit_project_path(project) %> |
        <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
      </div>

    
  <% end %>
</div>

app/views/projects/new.html.erb
<div class="row">
	<div class="col-md-offset-1 col-md-10">

		<h3>New project</h3>

		<%= render 'form' %>
		<p>
			<%= link_to 'Back', projects_path %>
		</p>

	</div>
</div>

app/views/projects/show.html.erb
<h3><%= @project.title %></h3>

<div role="tabpanel">

<!-- Nav tabs -->
<ul class="nav nav-tabs nav-justified" role="tablist" id="go">
  <li role="presentation" class="active"><a href="#status" aria-controls="status" role="tab" data-toggle="tab">Milestones</a></li>
<!--   <li role="presentation"><a href="#description" aria-controls="description" role="tab" data-toggle="tab">Description</a></li> -->
  <li role="presentation"><a href="#general" aria-controls="general" role="tab" data-toggle="tab">General Info</a></li>
  <li role="presentation"><a href="#schedule" aria-controls="schedule" role="tab" data-toggle="tab">Schedule</a></li>
  <li role="presentation"><a href="#budget" aria-controls="budget" role="tab" data-toggle="tab">Budget</a></li>
  <li role="presentation"><a href="#reports" aria-controls="reports" role="tab" data-toggle="tab">Reports</a></li>
  <li role="presentation"><a href="#team" aria-controls="team" role="tab" data-toggle="tab">Team</a></li>
  <li role="presentation"><a href="#images" aria-controls="images" role="tab" data-toggle="tab">Images</a></li>

<!-- Tab panes -->




<div class="tab-content">

  <div role="tabpanel" class="tab-pane active" id="status">
     
      <div class="panel panel-info">
         <% @project.statuses.each do |status| %>
        <div class="panel-heading">
          <h4 class="panel-title"><%= status.status_title %></h4>
        </div>
        <div class="panel-body">
            <%= simple_format(status.status_update) %>
        </div>
        <div class="panel-footer"><h6>Posted by <%= status.user.employee_name %> on <%= status.created_at.strftime("%D")%></h6>
            </div>
          <% end %>
      </div>
      
     <div class="add-report">
      <%= link_to "Add Status Update", new_project_status_path(@project, @status), class: 'btn btn-primary' %>
    </div>
   
  </div>



  <div role="tabpanel" class="tab-pane" id="description">
    <div class="form-inputs">
      <div class="panel panel-default">
        
        <div class="panel-body">
          <strong>Description:</strong>
          <p>
            <%= simple_format(@project.description) %>
          </p>
        </div>
      </div>
    </div>
  </div>




  <div role="tabpanel" class="tab-pane" id="general">
    <ul class="list-group">
         <li class="list-group-item">
          <strong>Description:</strong>
          <p>
            <%= simple_format(@project.description) %>
          </p>
        </li>
        <li class="list-group-item">
          <strong>Phase:</strong>
          <%= @project.phase %>        
        </li>
        <li class="list-group-item">
          <strong>Location:</strong>
          <%= @project.location %>
        </li>
        <li class="list-group-item">
          <strong>Area:</strong>
          <%= @project.area %>
        </li>
        <li class="list-group-item">
          <strong>Client:</strong>
          <%= @project.client %>
        </li>
        <li class="list-group-item">
          <strong>Designer:</strong>
          <%= @project.designer %>
        </li>
       <li class="list-group-item">
          <strong>Contractor:</strong>
          <%= @project.contractor %>
       </li>
    </ul>
  </div>




  <div role="tabpanel" class="tab-pane" id="schedule">
    <ul class="list-group">
        <li class="list-group-item">
          <strong>Project Start Date:</strong>
          <%= @project.project_start %>
        </li>
        <li class="list-group-item">
          <strong>Expected Completion Date:</strong>
          <%= @project.expected_date %>
        </li>
        <li class="list-group-item">
 
          <strong>Date of Contract Signature:</strong>
          <%= @project.signature_date %>
        </li>

       <li class="list-group-item">
          <strong>Construction Period (Months):</strong>
          <%= @project.construction_period %> months
      </li>
      <li class="list-group-item">
        <strong>Expected Stage:</strong>
        <%= progress_bar 0.4, label: true, alternative: 'success' %>
      </li>
      <li class="list-group-item">
        <strong>Actual Stage:</strong>
        <%= progress_bar 0.3, label: true, alternative: 'warning' %>
      </li>
    </ul>
  </div>

 
      

  <div role="tabpanel" class="tab-pane" id="budget">
   <ul class="list-group">
     <li class="list-group-item">
        <strong>Designated Budget:</strong>
        <%= @project.budget %> KD
      </li>
      <li class="list-group-item">
        <strong>Design Cost:</strong>
        <%= @project.design_cost %> KD
      </li>
      <li class="list-group-item">
        <strong>Execution Cost:</strong>
        <%= @project.execution_cost %> KD
      </li>
    </ul>
  </div>


  <div role="tabpanel" class="tab-pane" id="reports">
    <table class="table table-striped">
      <tr>
        <th>Number</th>
        <th>Month</th>
        <th>Phase</th>
        <th>actions</th>
        
      </tr>

      <% @project.months.each do |month| %>
        <tr>
          <td>#&nbsp;<%= month.id %></td>
          <td><%= month.month_time %></td>
          <td><%= month.phase %></td>
          <td><% if month.user == current_user || current_user.admin? %>
            <%= link_to edit_project_month_path(@project, month), target: "_blank" do %>
          <i class="fa fa-pencil"></i>
          <% end %> | <%= link_to project_month_path(@project, month), method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i class="fa fa-trash-o"></i>
          <% end %> |
          <% end %> <%= link_to month.report.url, target: "_blank" do %> 
            <i class="fa fa-download"></i>
          <% end %></td>
        </tr>
      <% end %>
    </table>
    <div class="digg_pagination">
      <%= will_paginate @months, :container => false %>
    </div>
    <div class="add-report">
      <%= link_to "Add Monthly Report", new_project_month_path(@project, @month), class: 'btn btn-primary' %>
    </div>
  </div>


  <div role="tabpanel" class="tab-pane" id="team">
    <div class="form-inputs">
      <div class="panel panel-default">
        
        <div class="panel-body">
          <% @project.teams.each do |team| %>
            <p><strong>Team Member:</strong>&nbsp;&nbsp;<%= team.member %> - <%= team.role %> | <%= link_to project_team_path(@project, team), method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i class="fa fa-trash-o"></i> | <%= link_to edit_project_team_path(@project, team), target: "_blank" do %>
          <i class="fa fa-pencil"></i>
          <% end %> 
            <% end %></p>

          <% end %>
        </div>
      </div>
        <div class="add-report">
        
        <%= link_to 'Add Project Member', new_project_team_path(@project, @project.teams.first), class: 'btn btn-primary' %>
  
        </div> 
    </div>
  </div>


  <div role="tabpanel" class="tab-pane" id="images">
   <div class="form-inputs">
      <div class="panel panel-default">
       
        <div class="panel-body">
          <div id="photos">
            <% @project.pictures.each do |picture| %>
              <div class="pic">
                <%= image_tag picture.image.url(:medium) %>
               <%=  link_to 'Download file', picture.image.url %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

</div> 
</div>